---
title: "Canopy Openess Index in R"
author: "Edson Silva-Júnior"
format: 
  html:
    embed-resources: true
    toc: true
    toc-depth: 5
    toc-expand: 1
    toc-location: left
    toc-title: Tópicos
    number-sections: false
    df-print: paged
    smooth-scroll: true
execute: 
  cache: false
editor: visual
theme: 
  light: flatly
  dark: darkly
---

```{=html}
<style>
body {
text-align: justify;
font-size: 20px}
blockquote {
  background-color: #FAEFA6;
  padding: 10px;
  font-size: 14.5px
}
</style>
```

# **Packages**

```{r}
library(terra)

library(tidyverse)

library(tidyterra)

library(hemispheR)
```

# **Data**

## Importing

```{r}
images <- paste0("cropped-images/imagem", 1:4, ".png")

images
```

## Visualizing

```{r, warning=FALSE}
visualizing_canopy <- function(x){
  
  raster_bi <- terra::rast(x)
  
  ggplots <- ggplot() +
    tidyterra::geom_spatraster_rgb(data = raster_bi) +
    scale_fill_continuous(na.value = "transparent") +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) 
  
  print(ggplots)
  
}

purrr::walk(images, visualizing_canopy)
```

# **Calculating Canopy Openess**

## Visualizing

```{r}
canopy_visualizing <- function(x){ 
  
  analy <- stringr::str_glue("analysis for {x}") 
  
  file <- x  |>
    hemispheR::import_fisheye()  |>
    hemispheR::binarize_fisheye()

  ggplt <- ggplot() +
    tidyterra::geom_spatraster(data = file) +
    scale_fill_viridis_c(na.value = "transparent", breaks = seq(0, 1, 1)) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    labs(title = analy) +
    theme_bw()
  
  print(ggplt)
  
}

purrr::walk(images, canopy_visualizing)
```

## Calculating

```{r}
canopy_Openess <- function(x){
  
  stringr::str_glue("analysis for {x}") |> message()
  
  raster <- x |>
    hemispheR::import_fisheye() |>
    hemispheR::binarize_fisheye()
  
  values_0 <- raster[raster > 0] |> terra::ncell()
  
  values_all <- raster |> terra::ncell()
  
  result <- values_0 / values_all
  
  print(result)
  
}

purrr::walk(images, canopy_Openess)
```
