---
title: "Índice de Abertura de Dossel"
author: "Edson Silva-Júnior"
format: 
  html:
    embed-resources: true
    toc: true
    toc-depth: 5
    toc-expand: 1
    toc-location: left
    toc-title: Tópicos
    number-sections: false
    df-print: paged
    smooth-scroll: true
execute: 
  cache: false
editor: visual
theme: 
  light: flatly
  dark: darkly
---

```{=html}
<style>
body {
text-align: justify;
font-size: 20px}
blockquote {
  background-color: #FAEFA6;
  padding: 10px;
  font-size: 14.5px
}
</style>
```
# **Pacotes**

```{r}
library(tidyverse)

library(tidyterra)

library(terra)

library(raster)

library(LAI)
```

# **Dados**

## Importando

```{r}
imagem1 <- terra::rast("./cropped-images/imagem1.png")

imagem2 <- terra::rast("./cropped-images/imagem2.png")

imagem3 <- terra::rast("./cropped-images/imagem3.png")

imagem4 <- terra::rast("./cropped-images/imagem4.png")
```

## Visualizando

```{r}
ggplot() +
  tidyterra::geom_spatraster_rgb(data = imagem1) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))

ggplot() +
  tidyterra::geom_spatraster_rgb(data = imagem2) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))

ggplot() +
  tidyterra::geom_spatraster_rgb(data = imagem3) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))

ggplot() +
  tidyterra::geom_spatraster_rgb(data = imagem4) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))
```

# **Binarizando a imagem**

## Binarizando

```{r, warning=FALSE}
LAI::unimodal_threshold(imagem1 %>% raster::raster()) %>% 
  plot(useRaster = TRUE)

LAI::unimodal_threshold(imagem2 %>% raster::raster()) %>% 
  plot(useRaster = TRUE)

LAI::unimodal_threshold(imagem3 %>% raster::raster()) %>% 
  plot(useRaster = TRUE)

LAI::unimodal_threshold(imagem4 %>% raster::raster()) %>% 
  plot(useRaster = TRUE)
```

## Índices

```{r, warning=FALSE}
# Imagem 1

n1 <- LAI::unimodal_threshold(imagem1 %>% raster::raster()) %>% 
  as.data.frame(xy = TRUE) %>% 
  na.omit() %>% 
  nrow()

n0_1 <- LAI::unimodal_threshold(imagem1 %>% raster::raster()) %>% 
  as.data.frame(xy = TRUE) %>% 
  na.omit() %>% 
  dplyr::filter(imagem1_1 == 0) %>% 
  nrow()

n0_1 / n1

# Imagem 2

n2 <- LAI::unimodal_threshold(imagem2 %>% raster::raster()) %>% 
  as.data.frame(xy = TRUE) %>% 
  na.omit() %>% 
  nrow()

n0_2 <- LAI::unimodal_threshold(imagem2 %>% raster::raster()) %>% 
  as.data.frame(xy = TRUE) %>% 
  na.omit() %>% 
  dplyr::filter(imagem2_1 == 0) %>% 
  nrow()

n0_2 / n2

# Imagem 3

n3 <- LAI::unimodal_threshold(imagem3 %>% raster::raster()) %>% 
  as.data.frame(xy = TRUE) %>% 
  na.omit() %>% 
  nrow()

n0_3 <- LAI::unimodal_threshold(imagem3 %>% raster::raster()) %>% 
  as.data.frame(xy = TRUE) %>% 
  na.omit() %>% 
  dplyr::filter(imagem3_1 == 0) %>% 
  nrow()

n0_3 / n3

# Imagem 1

n4 <- LAI::unimodal_threshold(imagem4 %>% raster::raster()) %>% 
  as.data.frame(xy = TRUE) %>% 
  na.omit() %>% 
  nrow()

n0_4 <- LAI::unimodal_threshold(imagem4 %>% raster::raster()) %>% 
  as.data.frame(xy = TRUE) %>% 
  na.omit() %>% 
  dplyr::filter(imagem4_1 == 0) %>% 
  nrow()

n0_4 / n4
```
